# Generated by Django 5.2 on 2026-05-30 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeScale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='variant',
            name='barcode',
        ),
        migrations.AddField(
            model_name='products',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='variant',
            name='size',
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('size_scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='product.sizescale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='variant',
            name='size_scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.sizescale'),
        ),
        migrations.AddField(
            model_name='variant',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, related_name='variants', to='product.size'),
        ),
    ]
