# Generated by Django 5.2 on 2026-06-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('printer_name', models.CharField(default='Xprinter XP-365B', max_length=255)),
                ('paper_width_mm', models.IntegerField(default=40)),
                ('paper_height_mm', models.IntegerField(default=30)),
                ('dpi', models.IntegerField(default=203)),
                ('layout_config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
