# Generated by Django 5.2 on 2026-06-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_client_created_by_paymentmenthod_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmenthod',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
