# Generated by Django 5.2 on 2026-06-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('manager', 'Manager'), ('senior_seller', 'Senior Seller'), ('junior_seller', 'Junior Seller')], default='junior_seller', max_length=20),
        ),
    ]
